### ISSUE TITLE
Implement conditional PDF

### ISSUE THREAD

**Issue by apuignav** [zfit/zfit#135]
What is needed? Probably we need a special type of PDF.

**Comment by jgpardinas** [comment]
Proposed new objects with needed features:

 **- Conditional PDF:**
   * Mathematical definition: PDFC(x_i;y_i|lambda_i) = f(x_i,y_i,lambda_i)/integral(dx'_i f(x'_i,y_i,lambda_i))
      where x_i are the "normal" observables, y_i are the conditional observables and lambda_i are the physical parameters
   * Evaluate method (numerator): f(x_i,y_i,lambda_i)
   * Total integral (normalization): integral(dx'_i f(x'_i,y_i,lambda_i))
   * Partial integral (numerator for plotting): integral(dx'_k f(x'_i,y_i,lambda_i))
      where x_k is a subset of x_i
   * Data member: y_i (list of conditional parameters, maybe just identified by the name)
   * Generate method: normal generation, note that the model will using the current value of y_i

 **- "Full" PDF:**
   * Mathematical definition: PDFF(x_i,y_i|lambda_i) = PDFC(x_i;y_i|lambda_i) x PDFM(y_i)
      where PDFM(y_i) is a marginal PDF (normal PDF, but directly taken from the data distribution on the
      conditional parameters)
   * Comment: similar constructor as for a PDF product combination, but with only two inputs. The list 
      of conditional observables can be read from the conditional PDF (first argument) and cross-
      checked with the space of the marginal PDF (second argument). It may usually be the case that the
      marginal PDF is itself a product of several 1D PDFs, one for each y parameter.
   * Evaluate method: product of the numerators
   * Normalization: integral(dy'_i PDFM(y'_i) integral(dx'_i f(x'_i,y'_i,lambda_i))
   * Partial integral: integral(dy'_i PDFM(y'_i) integral(dx'_k f(x'_i,y'_i,lambda_i))
      where x_k is a subset of x_i
   * Fit: for fitting, PDFM(y_i) should not be needed (it does not depend on lambda_i, so in principle can 
      be safely removed for this purpose, to reduce unnecessary computations)
   * Generation: first generate y_i values with PDFM(y_i); then, for each y_i, generate x_i with PDFC(x_i;y_i|lambda_i)

**Comment by mayou36** [comment]
Implemented a first version, slow but does the job
