### ISSUE TITLE
Implementation of kernel density PDF

### ISSUE THREAD

**Issue by abhijitm08** [zfit/zfit#138]
Implementation of Kernel density estimate. 

I have a very very preliminary implementation for 1D case here: https://drive.google.com/file/d/14wE2gFjgSVjtSDypOaaKPTshxuek9qDF/view?usp=sharing. 

However, need to:
1. Properly take into account the boundary effects.
2. Provide an option of taking the weights into account rather than assigning a weight of 1 to each data point.
3. Generalise it to multidimensional case.

**Comment by mayou36** [comment]
I'm implementing something. Is it engough to provide a static kernel width? So one value for all kernels? Or some addaptive procedure taking local points or similar into account?

**Comment by abhijitm08** [comment]
We ought to pick a bandwidth that optimises the AMISE at each given point. However the underlying function will not be known. The adaptive methods that choose this bandwidth would be way better than optimising for a global one (specially at high curvature regions). I think initially a global/static bandwidth, optimised with some data driven procedure, would be a good start.

**Comment by abhijitm08** [comment]
Hey, Here is the multidimensional KDE where the global bandwidth is optimised using MSE. As we discussed we ought to optimise the local correction to the global bandwidth (like sklearn does) using KD tree or ball algorithm. We can discuss more about this later:

https://colab.research.google.com/drive/1GW1XBcw2fJGor45biFFPCJzsBeE6apyK

**Comment by mayou36** [comment]
I've implemented something in https://github.com/zfit/zfit-physics/pull/1
Global bandwidth and Gaussian Kernel currently, I am working on something more general (zfit branch "kde2")

It's available in the namespace `zphys.unstable.pdf.GaussianKDE`

**Comment by mayou36** [comment]
An improved version is now available in `zfit.pdf.GaussianKDE1DimV1`. It's called V1 since it will be upgraded in the future (most probably), but supports adaptive kernel (currently just the GitHub version)
