### ISSUE TITLE
Implementation of multidimensional binned fit (independent of pyhf)

### ISSUE THREAD

**Issue by abhijitm08** [zfit/zfit#139]
I have the code for simple template fit (need to convert of binned fit) in pure TF. https://colab.research.google.com/drive/13RR8ePrVtpdvaVp5MmyUQHbs0UcflH7i 

Need to get this integrated with zfit. However, we need to discuss:

1) How the data is should be handled (just use the output of np.histogramdd? There is a TF function 'tf.histogram_fixed_width_bins' but only for 1D.)
2) If the PDF is continuous and not a template, provide the user the option of evaluating the PDF either at the bin centre or integrating b/w the bin boundaries.

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-development #38](https://github.com/zfit/zfit-development/issues/38) via [**ZenHub**](https://www.zenhub.com/)
