### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by mayou36** [zfit/zfit#14]
It would probably be nice to discuss/write down the conventions to be used in the package here in order to stay consistent.

Conventions (and my proposals):
- English: AE vs BE (AE; as used in most other packages)
- Docstyle: numpy vs google vs others (google; as in analysis-tools)
- naming conventions: PEP8 throughout or partial (throughout; implies changes but for a long term project a must have I think)
- line-length 100/120
- Unit testing: pytest vs unittest (pytest; as in analysis-tools)

More? Any thoughts?

**Comment by apuignav** [comment]
I agree. There's just a few things of pep8 that I don't like, but we can discuss on a case by case basis.

Also, should we enforce some kind of linting?

**Comment by mayou36** [comment]
Sure, agree! Same as in analysis-tools I guess.

Yes, some sort would be nice. I think CodeClimate etc. already check for a lot of things and while there are *now* a lot of issues around, after a clean-up (renaming etc.), this should go to zero. Any non-pylint compatible thing will pop up there and can easily be discussed on a case-by-case basis (but as it is reported as an error, it is some kind of "lint-enforcment").

Proposal: report lint score, see how CodeClimate etc work and figure out a reasonable "enforcement"

**Comment by apuignav** [comment]
Sounds like a plan.

**Comment by rsilvaco** [comment]
Can I just comment on the "English: AE vs BE". I do agree that most of the packages use the AE, but I really dislike it :( Even "flavor" instead of "flavour" looks horrible to me. Would it be too much hassle to use BE?

**Comment by apuignav** [comment]
I honestly don't mind

**Comment by mayou36** [comment]
Okey, so I would prefer some words like "minimize" to be AE as it is everywhere else as well. But, honestly, we can mix (and leave "flavour"). I don't mind.

Otherwise, after talking back with Rafael, AE for the code and BE for the docs is fine I think. So let's leave as is and change if someone bothers, ok?

**Comment by apuignav** [comment]
Fine for me

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #9](https://github.com/zfit/zfit-developement/issues/9) via [**ZenHub**](https://www.zenhub.com/)
