### ISSUE TITLE
Possible extra splitting of the amplitude (for TD fits)

### ISSUE THREAD

**Issue by jgpardinas** [zfit/zfit#141]
For angular/mass fits the square of the total amplitude is factorized as Re(ci cj* Ai Aj*), where Ai contain the dependence on the angles and masses.
For fitting, when the Ai terms are constant, they and their integrals can be cached.

In the case of decay-time-dependent fits, the ci terms would develop a time dependency and they could be expressed as a sum of four constant parameters multiplied each of them by a time-dependent function (trigonometric and hyperbolic cosines).
In this case, it would be convenient to further split these terms to also cache the time-dependent functions and their integrals.

**Comment by apuignav** [comment]
Moving to https://gitlab.cern.ch/apuignav/zfit-amplitude/issues/11.
