### ISSUE TITLE
Bug with GaussianConstraint

### ISSUE THREAD

**Issue by marinang** [zfit/zfit#162]
I want to add 3 constraints to a likelihood, see dummy example:

```python

const1 = zfit.Parameter("const1",  1.0)
const2 = zfit.Parameter("const2",  2.0)
const3 = zfit.Parameter("const3",  3.0)

constraint = {"params": [const1, const2, const3],
                        "mu": [1.0, 2.0, 3.0],
                        "sigma": [0.05, 0.05, 0.05]}

nll.add_constraints(zfit.constraint.GaussianConstraint(**constraint))

```
So this works but when I minimise the likelihood the parameters are not even close the the central value of the parameter and even if I put limits to the parameters this doesn't change anything (or the parameters are a the limits after the minimisation).

On the other hand If I do 

```python

const1 = zfit.Parameter("const1",  1.0)
const2 = zfit.Parameter("const2",  2.0)
const3 = zfit.Parameter("const3",  3.0)

constraint = {"params": [const1, const2],
                        "mu": [1.0, 2.0],
                        "sigma": [0.05, 0.05]}

nll.add_constraints(zfit.constraint.GaussianConstraint(**constraint))
nll.add_constraints(zfit.constraint.GaussianConstraint(params=const3, mu=const3, sigma=0.05))
```
It works perfectly ... the parameters are very close the central values of the constraints.
I have not clue yet why this happens.

## Context (Environment)

* zfit version: 0.3.3
* Python version: 3.6.7
* Are you using conda, pipenv, etc? : Conda
* Operating System: MacOS
* Tensorflow version: 1.13.1

**Comment by mayou36** [comment]
That's odd, just for the record: the true value of param3 is 3ish?

Maybe some indices are mixed up in the Gaussian constraint or something?

I can have a look next week I think, feel free to investigate and re-check our implementation. But odd...
