### ISSUE TITLE
Implement a repository of models

### ISSUE THREAD

**Issue by apuignav** [zfit/zfit#17]
We should implement a system/repository to upload models once papers are published, sort of `pypi` for models. My idea is that it's a python package that uses a local version and if you don't have a local version it goes to a central server to grab the models.

I leave this here, but it's not urgent. We can start the discussion though, so we know exactly what to do.

**Comment by mayou36** [comment]
We've been to a [TF Hub](https://www.tensorflow.org/hub/) talk, this seems to be what we looked for to store graphs.

In short: in the hub (cloud), a tf graph can be stored with a defined (by us) API on what is variable ("trainable"), what not and where input goes in/out. Loading/caching already implemented.

@rsilvaco is also in favor of that. Opinion, @apuignav ?

**Comment by apuignav** [comment]
Let's do it.

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #16](https://github.com/zfit/zfit-developement/issues/16) via [**ZenHub**](https://www.zenhub.com/)
