### ISSUE TITLE
[BUG] Parameter with no range set, is by default non floating

### ISSUE THREAD

**Issue by marinang** [zfit/zfit#177]
If I do 

```python
>>> mean = zfit.Parameter("mean", 1.0)
>>> mean.floating 
False
```

I wouldn't expect it to be the default behaviour. I just saw #176, is this something you are planning to warn the users?

**Comment by mayou36** [comment]
This is in fact a bug. The behavior should be that this is floating. I have an idea though why it happens... I'll check.

#176 is about something different: if you set the parameter to not floating but give it explicitly to `minimize` of a minimizer, should it float or not?

_(Though some people mentioned that they would expect it to be not floating :sweat_smile:)_

**Comment by mayou36** [comment]
Hm, I cannot reproduce the behavior. For me, the above returns `True`. Are you sure that this is the exact output? Which version are you using? I have tested against develop and (conda) 0.3.6.

**Comment by marinang** [comment]
I have just upgraded to 0.3.6 and don't see the bug. Maybe I had a glitch xD
