### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by apuignav** [zfit/zfit#18]
We should create a `Docker` container for the releases, so people can just fire it up and immediately use `zfit`, for example to test a model. This could be very useful, especially given the fact that `tensorflow` is not always easy to install...

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #19](https://github.com/zfit/zfit-developement/issues/19) via [**ZenHub**](https://www.zenhub.com/)
