### ISSUE TITLE
Cannot perform error calculation 'minos_minuit' with a different minimizer then`Minuit`.

### ISSUE THREAD

**Issue by ulorentz** [zfit/zfit#181]
I tried to compute the error after fitting with Adam and not Minuit. Apparently this is not possible. 
## Current Behaviour

```# minimize
minimizer = zfit.minimize.Adam()
result = minimizer.minimize(nll)

# calculate errors
param_errors = result.error()
```
The output was: 
```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-17-3f8fdd90f0cd> in <module>()
      3 
      4 # calculate errors
----> 5 param_errors = result.error()

2 frames

/usr/local/lib/python3.6/dist-packages/zfit/minimizers/fitresult.py in _minos_minuit(result, params, sigma)
     48     from zfit.minimizers.minimizer_minuit import Minuit
     49     if not isinstance(minimizer, Minuit):
---> 50         raise TypeError("Cannot perform error calculation 'minos_minuit' with a different minimizer then"
     51                         "`Minuit`.")
     52     result = [minimizer._minuit_minimizer.minos(var=p.name, sigma=sigma)

TypeError: Cannot perform error calculation 'minos_minuit' with a different minimizer then`Minuit`.
```
## Expected Behaviour
I would expect all the three included optimizer to be able to run the error computation.
## Context (Environment)

* zfit version: '0.3.6'
* Python version: '3.6'
* Are you using conda, pipenv, etc? : No, plain python with zfit installed via pip
* Operating System: Debian
* Tensorflow version: 1.14

**Comment by marinang** [comment]
Hello @ulorentz, as the name indicates the optimizer optimizes, in our case to find the minimum of a loss function but doesn’t do error computations.

The Hesse and Minos method to compute errors are part of the Minuit package which contains a minimizer/optimizer called Migrad.

Hesse compute the errors by inverting the hessian matrix, Minos by profiling the likelihood. So these methods can be implemented in zfit, but it is not the case yet that’s why it works only with Minuit. We discussed about that a while ago  with @mayou36 , what the status about that.

Regarding Minos, in hepstat https://github.com/scikit-hep/hepstats we do profile likelihood computation which can be used to compute the asymmetric errors.

**Comment by apuignav** [comment]
Just to add to what @marinang said, the idea of `error` is to provide CPU-intensive error calculation, which may or may not be implemented for a given minimizer (a hole which `hepstats` can certainly help to fill). The `hesse` errors should be calculated for every minimizer, as they are cheap to calculate but come with quite a few caveats.

I agree the docs are not clear on this point, we'll improve them.

**Comment by mayou36** [comment]
To add: why do you want to fit with Adam? While you can surely do that, in most cases you will have worse performance than with minuit.
