### ISSUE TITLE
Implementing custom PDF

### ISSUE THREAD

**Issue by chm-ipmu** [zfit/zfit#182]
I want to implement something like a RooGenericPdf, where I simply specify a function and a list of parameters and get a PDF returned.

My understanding from the documentation is that to do this I must create a subclass of zfit.pdf.ZPDF.  I found that the documentation was a bit implicit and did not explain the details of creating one's own PDF.

I think there is a mistake in your documentation (https://zfit.readthedocs.io/en/latest/model.html), namely "_unnormalized_pdf" should be a method of MyGauss (it isn't indented). Also, could you explain why _unnormalized_pdf takes x as a parameter but doesn't use it? Should the first line be x = ztf.unstack_x(x)?

Cheers,
Colm

**Comment by marinang** [comment]
@mayou36 would `SimplePDF` (see https://github.com/zfit/zfit/blob/f4c2f2be481167a2362368f0aa36ee91bdb07c0b/zfit/models/special.py) work for @chm-ipmu  case ?

About the documentation, indeed the indeed is missing, and indeed it should be `x = ztf.unstack_x(x)`.

**Comment by chm-ipmu** [comment]
@marinang  Thanks for the info. Is there a usage example of SimplePDF?

Also, I have a question: If I want to use a non-floating Parameter with an uncertainty, can I propagate that uncertainty to other dependent quantities? For example, in RooFit you may have a constant RooRealVar and then call RooRealVar::setError(x) to set the error to be propagated as x. I do not see any similar sounding API calls in the zfit.Parameter page.

Thank you!

**Comment by mayou36** [comment]
You're correct, there is a typo in the docs, thanks for pointing it out.

I would propose to use the class and inherit from it as you've done. You may wanna have a look at the [examples](https://github.com/zfit/zfit/tree/develop/examples), which provide also the possibility to implement more complex usecases.

In which sense would you want the error to be propagated? I agree that it is needed for the chi2 fit.

**Comment by chm-ipmu** [comment]
No worries. I think I have got my class up and running as expected.

As for the error propagation: let's say my function depends on a 
constant, which is really a physical observable which has been measured 
with some finite degree of precision. How can I ensure that the 
uncertainty on this (fixed) parameter is properly propagated to the 
dependent floating observables, which I measure during the fit?

**Comment by chm-ipmu** [comment]
No worries. I think I have got my class up and running as expected.

As for the error propagation: let's say my function depends on a constant, which is really a physical observable which has been measured with some finite degree of precision. How can I ensure that the uncertainty on this (fixed) parameter is properly propagated to the dependent floating observables, which I measure during the fit?

**Comment by mayou36** [comment]
What do you mean by "propagated"? And if it is a fixed parameter, there is, conceptually speaking, also no uncertainty I think?

What you may look for are constraints: let the parameter float and add e.g. a Gaussian constraint, which reflects the prior knowledge of the parameter.

To estimate the error of a POI, I would propose to use the "hesse" or "error" methods of the fitresult (or even better, go to [hepstats](https://github.com/scikit-hep/hepstats) to do profile likelihoods etc.). Using the constraint, this perfectly incorporates the measured uncerstainties.

**Comment by chm-ipmu** [comment]
I am betraying my lack of deep knowledge in the subject here, but I believe in RooFit if one has a parameter which does not float in the fit then it is still possible to accommodate its measured uncertainty by using .setError(), but I could be wrong. I thought that this meant that the uncertainty associated with the parameter is used when the fit uncertainties of the floating parameters are calculated.

Regardless, the Gaussian constraint looks like what I need and I've tested it as working. 

Thanks for your help, and good luck with the project!

**Comment by mayou36** [comment]
That's good to know. Can I may ask what fits you are performing? It is quite useful for us to know the use-cases. If you want, you can also write me on mail, jonas.eschle@cern.ch

And thanks!
