### ISSUE TITLE
Missing warning/error when a Parameter is set with a value outside its limits

### ISSUE THREAD

**Issue by marinang** [zfit/zfit#188]
## Current Behaviour

When parameter with limits is set to a value outside of its limits, no warning/error is raised. It was particularly odd for me when doing parameter combinations.

```python 
>>> sigma = zfit.Parameter("sigma", 1.0, 0.0, 2.0)

>>> with sigma.set_value(10):
        print(zfit.run(sigma))
        print(zfit.run(sigma + 1.))
10.0
3.0

>>> with sigma.set_value(3.0):
    print(zfit.run(sigma))
    print(zfit.run(sigma + 1.))
3.0
3.0

>>> with sigma.set_value(4.0):
    print(zfit.run(sigma))
    print(zfit.run(sigma + 1.))
4.0
3.0
```

## Expected Behaviour
The `set_value` should raise a warning or an error. A warning can be easily not looked at (or even hidden) so and error would avoid anything unexpected.

## Context (Environment)
* zfit version: 0.3.6 and 0.4.1
* Python version: 3.6.5
* Are you using conda, pipenv, etc? : conda
* Operating System: MacOS
* Tensorflow version: 1.14.0 and 2.0.0

**Comment by mayou36** [comment]
Thanks for that! This behavior is in fact an open issue.

Putting an error there sounds would be my preferred solution as well. But there are maybe use-cases to clip a value, in a minimizer it can be quite usefule (as the gradients are preserved)? If so, should we make it an option on set_value or instantiation or similar?

e.g. `Parameter.set_value(1., clip=True)`

We could change the behavior to `error` and add an `experimental_clip` argument to allow to switch the behavior.

**Comment by mayou36** [comment]
Currently, we added a `at_limit` flag for parameters. Do you think this is already enough or rather more?

**Comment by marinang** [comment]
@mayou36 the attribute may be useful, I don't see yet how.  If this is enough or not, I don't know, at least I know the issue but will the user base of zfit actually encounter that problem, maybe not.

This can be an issue in `hepstats` when a user defines a scan range that is larger than the limits of the parameter of interest and very weird results are computed. An error can be raised in `hepstats` when this happens.

**Comment by mayou36** [comment]
We can also create a runtime error, this still seems quite fine to me.
Other than that, the loss could check the params. It could make sense to have a `valid` attribute, not just `converged`. This could also be invalidated when e.g. another minimum was found

**Comment by marinang** [comment]
> We can also create a runtime error, this still seems quite fine to me.
If if doesn't affect anything else, I am up for it.

> Other than that, the loss could check the params. It could make sense to have a `valid` attribute, not just `converged`. This could also be invalidated when e.g. another minimum was found
You are speaking about something else right?

**Comment by mayou36** [comment]
> You are speaking about something else right? In PR #214 I added a `valid` attribute in `FitResult` by the way.

Yes, that's the attribute I meant. I think it should be mutable (given its purpose in #214 and could check several subattributes, such as `is_global_min`, `params_at_limit`, `converged`.

Whatever the exact cause of the failure is a different story, but it makes for a simple, consistent flag. What do you think?

**Comment by marinang** [comment]
Yep agreed. About the `is_global_min`  attribute, should it be set to `True` after a minimum is found and then changed when `.error()` find a new minimum?

**Comment by mayou36** [comment]
Yes, exactly.
I was also thinking to improve two things for readability:
 - parameter displayed: create a 'parameter object' (a dict basically), with a nice readable presentation
 - status displayed: give a nice output of the fit result, including 'valid' and the reasons why not

**Comment by marinang** [comment]
Yeah improving the parameter and status display is a good idea, do you think of a display like it is done in `iminuit` ?
I realised that in the future calling `hesse` implemented here won't use the nice display of `iminuit`  hesse function where the correlation matrix is shown etc... useful to debug a fit or design a model. But actually sometime the nice `iminuit` , after upgrading  an environment especially, is not shown.

**Comment by mayou36** [comment]
Yes, something in the order of iminuit, also with colors (e.g. if a param is at its limits)
To get the information out easier

**Comment by mayou36** [comment]
Fixed by raising an error if outside. There is an assign method that does not raise
