### ISSUE TITLE
hesse_np is not correct

### ISSUE THREAD

**Issue by marinang** [zfit/zfit#208]
## Current Behaviour

```python 
def _hesse_np(result: "FitResult", params, sigma=1.0):
    if sigma != 1.0:
        raise ValueError("sigma other then 1 is not valid for hesse numpy.")

    # check if no weights in data
    if any([data.weights is not None for data in result.loss.data]):
        raise WeightsNotImplementedError("Weights are not supported with hesse numpy.")

    # minimizer = fitresult.minimizer
    # from zfit.minimizers.minimizer_minuit import Minuit
    # if not isinstance(minimizer, Minuit):
    #     raise TypeError("Cannot perform hesse error calculation 'minuit' with a different minimizer then"
    #                     "`Minuit`.")
    result_hesse = 2 * np.linalg.inv(result.loss.value_gradients_hessian(params)[2])

    hesse = OrderedDict((param, {'error': result_hesse[i, i]}) for i, param in enumerate(params))
    return hesse
```

First of all, I don't understand the factor 2, `result_hesse` should be actually the covariance matrix. I compared with the value of `result_hesse` and `covariance` and now `covariance == 2 * result_hesse`. 

Second of all, the errors should be the square roots of the diagonal elements.

## Possible Solution/Implementation

I would replace the last lines by, 

```python
    covariance = np.linalg.inv(result.loss.value_gradients_hessian(params)[2])

    hesse = OrderedDict((param, {'error': covariance[i, I]}**0.5) for i, param in enumerate(params))
    return hesse
```
 
I would like to make a PR implementing those changes and also make the `covariance` method available for the other minimiser, and add tests.

**Comment by marinang** [comment]
This an example.

![Capture d’écran 2020-03-10 à 13 48 56](https://user-images.githubusercontent.com/24250309/76313775-e6535b00-62d5-11ea-9a3f-b60897db8509.png)

**Comment by mayou36** [comment]
Hey, thanks for spotting, the factors of 2 is wrong of course, it should be a sqrt! Yes sure, this seems to be the wrong version actually, maybe git got mixed somewhere.

Please go ahead, that would be great! In fact, this can maybe also be refactored.

Sidenote: it can currently be quite slow due to using the analytic expression by default, I'll change that once I get fully the eager and numerical out

**Comment by marinang** [comment]
Yes indeed I noticed it is slow.

**Comment by marinang** [comment]
By the way in the `hesse` method the `params` attribute doesn't make sense I think because It means you consider those params as free parameter in the fit. If you select a subset the hessian matrix will be wrong and so the errors. 
It can still be kept if the hessian matrix is computed using all the parameters.
