### ISSUE TITLE
Compute parabolic errors by default

### ISSUE THREAD

**Issue by HDembinski** [zfit/zfit#226]
zfit computes MINOS errors by default, which is the wrong choice. zfit should compute parabolic (HESSE) errors by default. There is a reason that other tools use HESSE by default.

- MINOS takes longer to compute than HESSE
- MINOS does not give you a full covariance matrix that you need for error propagation

Even for mildly asymmetric errors, HESSE errors often have same coverage as MINOS errors. MINOS errors seem like they give more detail, but in reality they are less useful than HESSE errors. Nobody knows how to error propagate several parameters with MINOS errors, while this is straight-forward when you have the HESSE errors.

**Comment by marinang** [comment]
Using the `hesse` method instead of `error` of the `FitResult` and it will give you the error computed from the covariance matrix. You can get the covariance matrix using the `covariance` attribute.

**Comment by mayou36** [comment]
Hi Hans, first of all, thanks a lot for the feedback!

zfit does not compute any error by default, not even the hessian, but leaves the choice of it to the user. As @marinang mentioned, `result.error()` will return the "minos" (or a custom implementation) error, the "exact" one. On the other hand, `hesse` calculates the hessian error.

The idea is to avoid mistakes: `error` returns the "true" error, `hesse` the "hessian approximation". Would you propose to change something in this scheme? Or maybe this was not made clear in the docs/examples, would be great if you have a proposal where to put that best.

P.S: Maybe you'd like to have a look at the PR, any comment from you would be very welcome, given your expertise in this things: https://github.com/zfit/zfit/pull/214/files#diff-6e5b5fa9cd4693e13edbc7ae34a0f821R38, an custom implementation of MINOS, independent of the minimizer used.

**Comment by HDembinski** [comment]
1) MINOS errors are not "exact". They are based on the profile likelihood method, which is only asymptotically (large statistics) correct. And the same is true for the HESSE errors. They are just different ways to compute an uncertainty estimate. MINOS works better when you have a parameter with a limit close to the limit boundary. Otherwise, HESSE errors are preferred, because they are easier to work with.

2) The interface ".error()" is singular "error" instead of "errors". This suggest that you should get a single number, but you get two numbers. I think it would be better for ".error()" to return the HESSE error and then you could have ".confidence_interval()" to return what MINOS returns. Strictly speaking this is an approximate confidence interval.

3) Concerning, https://github.com/zfit/zfit/pull/214/files#diff-6e5b5fa9cd4693e13edbc7ae34a0f821R38, why don't you use the functionality in iminuit to compute this?

**Comment by marinang** [comment]
@HDembinski thanks for your feedback, and I agree on the overall practicability of hessian errors versus asymmetric errors, computed from the profiled likelihood, in your first point.

On your second point I also totally agree that it should be called at least `errors` for the reason that you get two numbers, and good point that about minos errors being an approximate CI. So a renaming should be considered I think, let's wait what @mayou36  thinks.

For the third point, `zfit` can use different minimisers other than `minuit` where `hesse` and `minos` are not implemented. I just saw that you edited your post, maybe it's preferable to not  be dependent of a particular minimiser ...

**Comment by mayou36** [comment]
Thanks a lot @HDembinski, this is very useful!

1. alright, I was not fully aware of this, actually. My general idea was that hesse is fine if the profile can be approximated well with second order while minos is good if this approximation does not hold. Which surely is the case close to boundaries, I agree.

2. I agree, naming it "errors" makes in fact more sense.

3. we currently use minos when the minuit minimizer is used, the demand for other minimizers (e.g. implemented in pure TF or nlopt etc) makes an implementation independent minos version (actually what you proposed above to do). Very glad to hear that with hesse, as the current numerical way of computing the hessian is very unstable in practice (using `numdifftools`). But maybe I also just don't know how to treat it right :)

**Comment by mayou36** [comment]
We changed (depreceated) `error` in favor of `errors`.
Feel free to close this issue

**Comment by HDembinski** [comment]
Thank you for reacting so well to this suggestion. Why not `.interval` instead of `errors` or maybe `error_interval`? I understand that you want to use as short a name as possible, but one should try to strike a balance between brevity and clarity.

**Comment by mayou36** [comment]
True, this is usually a tradeoff. We had several names in mind actually, these were our thoughts:
 - uncertainties: seems cumbersome to write/read
 - pll or similar: neither very accurate nor is the abbreviation "very well known" as others (e.g. NLL, pdf).
 - interval: maybe ambiguous in the context of a fit result. It could also mean some limits or similar
 - error/errors: Not a perfect accurate description (it's an uncertainty, not an "error") yet often used (error propagation,...) and unambiguous in this context; plus short and simple.

That's why we went for "error". But maybe you have other arguments or suggestions? Would you disagree with the arguments that "interval" is too ambiguous?
