### ISSUE TITLE
Change function parameters order of parameter.convert_to_parameter()

### ISSUE THREAD

**Issue by SebastianJL** [zfit/zfit#255]
ConstantParameter, ComposedParameter and ComplexParameter all have the following parameter order
```python
def __init__(self, name, value/value_fn, ...): ...
```
convert_to_parameter() on the other hand has the first two parameters switched:
```python
def convert_to_parameter(value, name): ...
```
I would exchange the two in order to be consistent with the rest of the module.

**Edit**
As `value` and `name` cannot be exchanged in `convert_to_parameter` -- because `name` is an optional parameter -- I would suggest to change the signature of all the `__init__()` methods if possible.

**Edit**
Ok I realize now that that's probably not possible as `name` also appears in other places as first parameter. Any other suggestions?

**Comment by Sangu80** [comment]
@SebastianJL can i solve this issue ?

**Comment by mayou36** [comment]
While I really dislike how it is, I have to admit that it maybe becomes a won't fix. The reasoning is that the `convert_to parameter` has a different Functionality and while it doesn't match with `Parameter`,e.g.`ComposedParameter` has a different signature anyway.
So I will close this.

@Sangu80 if you're interested to contribute, feel free to write us to zfit AT physik.uzh.ch
