### ISSUE TITLE
Software specs - limitations

### ISSUE THREAD

**Issue by mayou36** [zfit/zfit#26]
Documentation of limitations
============================

* Parameters and data are treated on a different foot and cannot simply be interchanged with each other

**Comment by apuignav** [comment]
Mmm, I am not sure I follow this... What's the idea of this limitation?

**Comment by mayou36** [comment]
Parameters are `tf.Variables` while data is not but feed in as constant tensors (or converted to them). RooFit allows to interchange them (think of a gaussian, mu or x can be interchanged, not in TF). Asked Rafa about it, he cannot think of a use-case where interchangeability could be useful. You have something in mind?

Just starting to document the software a little ;)

**Comment by apuignav** [comment]
Ah ok! Sure! However, I wouldn't say this is a limitation, it's almost by construction of a likelihood function, isn't it?

**Comment by mayou36** [comment]
Yes, I agree! But it's a difference to RooFit, so just document it. If no one cares, even better. One use case, that implicitly won't work with that, is that we can't integrate over a parameter.

**Comment by apuignav** [comment]
Mmm, that seems bad... @rsilvaco?

**Comment by mayou36** [comment]
Well, we can always define a different function with parameter a as dimension and explicit dependence. So instead of f(x; a, b) just f(x, a; b) -> integrate over a -> f(x; b). This should work out.

**Comment by rsilvaco** [comment]
Not sure if I understood the issue in here. I think from the point of view of our current fits, unless I'm missing something, I don't see the use case. In principle people may want to have it, but from my side I wouldn't put this as top priority....

**Comment by rsilvaco** [comment]
Yes @mayou36, is probably not strictly the same as RooFit does, but this should naively work ..

**Comment by apuignav** [comment]
Fine, we'll accept requests afterwards :-)

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #10](https://github.com/zfit/zfit-developement/issues/10) via [**ZenHub**](https://www.zenhub.com/)
