### ISSUE TITLE
zfit 0.5.2 does not seem to support Python 3.8 unlike the release notes say

### ISSUE THREAD

**Issue by eduardo-rodrigues** [zfit/zfit#268]
The release 0.5.2 - https://github.com/zfit/zfit/releases/tag/0.5.2 - states "Support for Python 3.8 with TensorFlow 2.2 version. Minor bugfixes." but I was not managing to get a consistent environment on Binder, so poked around and read from what is available on Conda that only Python 3.6 and 3.7 are available. There's a glitch somewhere. To check this, go to https://anaconda.org/conda-forge/zfit/files and click on the "i" info button under the Name column; you get that zfit 0.5.2 depends on "cloudpickle >=0.6.1, colorama, colored, colorlog, decorator, iminuit, numdifftools, numpy, ordered-set, pandas, python >=3.6,<3.8, scipy >=1.2, tabulate, tensorflow-base >=2.1.0, tensorflow-probability >=0.8.0, texttable, uproot".

Could this be a bug in the way 0.5.2 was made into Conda? This is all unfortunate because 0.5.2 is the most recent version available in Conda and that obliges to use Python 3.7.

**Comment by eduardo-rodrigues** [comment]
BTW, this is what I see in Binder when trying to do a `conda install zfit==0.5.2`:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - zfit==0.5.2 -> python[version='>=3.6,<3.8']

Your python: python[version='>=3.8,<3.9']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

**Comment by eduardo-rodrigues** [comment]
@mayou36, and I still see issues with zfit 0.5.2 and Python 3.7 (3.7.8 on Binder) when I do a `import zfit
`:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-fd7cc66c7088> in <module>
----> 1 import zfit

/srv/conda/envs/notebook/lib/python3.7/site-packages/zfit/__init__.py in <module>
     64                   f" will raise an error in the future.")
     65 
---> 66 from . import z
     67 from . import z as ztf  # legacy
     68 from .settings import ztypes

/srv/conda/envs/notebook/lib/python3.7/site-packages/zfit/z/__init__.py in <module>
     47 from .zextension import (to_complex, to_real, constant, pi, abs_square, nth_pow, unstack_x, stack_x, safe_where,
     48                          run_no_nan, function_tf_input, function_sampling, py_function)
---> 49 from . import random, math, unstable
     50 # math

/srv/conda/envs/notebook/lib/python3.7/site-packages/zfit/z/random.py in <module>
      4 
      5 import tensorflow as tf
----> 6 import tensorflow_probability as tfp
      7 
      8 from .zextension import function as function

/srv/conda/envs/notebook/lib/python3.7/site-packages/tensorflow_probability/__init__.py in <module>
     73 
     74 # from tensorflow_probability.google import staging  # DisableOnExport
---> 75 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     76 from tensorflow_probability.python.version import __version__
     77 # pylint: enable=g-import-not-at-top

/srv/conda/envs/notebook/lib/python3.7/site-packages/tensorflow_probability/python/__init__.py in <module>
     22 from tensorflow_probability.python import debugging
     23 from tensorflow_probability.python import distributions
---> 24 from tensorflow_probability.python import experimental
     25 from tensorflow_probability.python import glm
     26 from tensorflow_probability.python import layers

/srv/conda/envs/notebook/lib/python3.7/site-packages/tensorflow_probability/python/experimental/__init__.py in <module>
     32 from __future__ import print_function
     33 
---> 34 from tensorflow_probability.python.experimental import auto_batching
     35 from tensorflow_probability.python.experimental import edward2
     36 from tensorflow_probability.python.experimental import mcmc

/srv/conda/envs/notebook/lib/python3.7/site-packages/tensorflow_probability/python/experimental/auto_batching/__init__.py in <module>
     22 from tensorflow_probability.python.experimental.auto_batching import allocation_strategy
     23 from tensorflow_probability.python.experimental.auto_batching import dsl
---> 24 from tensorflow_probability.python.experimental.auto_batching import frontend
     25 from tensorflow_probability.python.experimental.auto_batching import instructions
     26 from tensorflow_probability.python.experimental.auto_batching import liveness

/srv/conda/envs/notebook/lib/python3.7/site-packages/tensorflow_probability/python/experimental/auto_batching/frontend.py in <module>
     44 from tensorflow.python.autograph.core import naming
     45 from tensorflow.python.autograph.pyct import anno
---> 46 from tensorflow.python.autograph.pyct import compiler
     47 from tensorflow.python.autograph.pyct import inspect_utils
     48 from tensorflow.python.autograph.pyct import parser

ImportError: cannot import name 'compiler' from 'tensorflow.python.autograph.pyct' (/srv/conda/envs/notebook/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/__init__.py)
```

Have you seen this before? Any idea?

**Comment by mayou36** [comment]
Hey, I can answer more later, but in short: you can't use the ananconda release unfortunately, the upstream packages are not added to anaconda. With pip it should all work

**Comment by eduardo-rodrigues** [comment]
I was going to swear that it worked find in conda when I did that tutorial at DESY back in early March :S. But I believe you. I will do some more tests and put conclusions here. Thanks a lot.

**Comment by eduardo-rodrigues** [comment]
OK, I tried with PyPI and indeed can import all I need, as one would expect. Cool.
I still need to add some notebooks but it seems I'm sorted. Thanks a lot!

The above features I mention about Conda are still weird, but that's a different matter. Feel free to close.

**Comment by marinang** [comment]
Maybe the environment.yml can be modified to install zfit with pip. That's what I am doing for hepstats.

**Comment by eduardo-rodrigues** [comment]
That's precisely what I did, @marinang :-).

**Comment by eduardo-rodrigues** [comment]
It's just that I try to use conda over pip where possible, since that seems the right default way.

**Comment by marinang** [comment]
@eduardo-rodrigues Ah sorry I understood that you wanted to use the zfit Binder (if it exists actually 🤔).

**Comment by mayou36** [comment]
@eduardo-rodrigues you're right, it worked back then. But we did not fix the TF release yet back then, now with new TF it breaks. And 0.5.2 was the newest back then I think.

I agree, I try to use conda as well whenever possible, unfortunately TensorFlow-Probability is stuck on the old versions, e.g. not available in conda, I've already wrote them, but there seems to be some more fundamental issues (https://github.com/conda-forge/tensorflow-probability-feedstock/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)

**Comment by eduardo-rodrigues** [comment]
I see ... Not much you can do there :S.

So it seems I have a working environment to show-case next week the many packages of the PyHEP ecosystem during some school lectures organised by Liverpool, and that was my main worry.

**Comment by mayou36** [comment]
Perfect! When are you gonna have them?

**Comment by eduardo-rodrigues** [comment]
Tuesday! I'm tight given too much work, but still hope to finalise some bits talking about new packages such as `Hist`.

**Comment by mayou36** [comment]
Okey, let me know in case you run into any problems, also available on the weekend
