### ISSUE TITLE
Data handling - API and specs

### ISSUE THREAD

**Issue by mayou36** [zfit/zfit#27]
First we need to get the data into a python/tf compatible format: #8 

Discussed strategy: using tf.data.Dataset and "wrapping" it in some kind (also recommended way in TensorFlow).

Collecting here all the requirements to our data format:

First priority:

- [ ] data: store the data (+ attributes like name)

- [ ] weights: IMHO, (event-)weights and data are one piece that *never ever* should be separated. I cannot think of a *single* use case, where data is used without weights (leaving aside the trivial case of data with weights 1). So the data format should contain the weights as well, know about them. This way, we just need one object to be passed around.

Second priority
- [ ] iteration: While not top priority, out-of-core computations should be implemented, typically with an iterator. Should be "easy" though, as this is a common big data problem.

- [ ] loading: given that out-of-core computations should work, loading (and auto-converting of data) has to be implemented as well.

Nice to have items:

- [ ] dumping: would be nice, but which data has to be dumped actually? Toys?

- [ ] plotting: like in pandas, it can be very convenient to simply plot the data (with the right weights applied).

**Comment by apuignav** [comment]
What about https://github.com/scikit-hep/awkward-array?

**Comment by mayou36** [comment]
That looks nice, but still quite early development as it seems.

But I think we need a slightly higher level interface, more like pandas. What I really always miss is the weights. I think they should be carried with the data "all the time". Right?

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #11](https://github.com/zfit/zfit-developement/issues/11) via [**ZenHub**](https://www.zenhub.com/)
