### ISSUE TITLE
Import dataset from a ROOT file with cut

### ISSUE THREAD

**Issue by XuelongQin** [zfit/zfit#273]
Hi!
I am trying to perform a fit to a tree. But I need to add some cut to the branches which are not the observables of the fit.
Website https://zfit.readthedocs.io/en/latest/getting_started/intro/data.html tells me that I can include cuts in the dataset by specifying the root_dir_options. But I don't know how to operate it.
For example, I want to open a ROOT file "test.root" with tree "ntuple". The observables of the fit is x.
I can write 
data = zfit.Data.from_root("tese.root","ntuple","x")
If I need to set cut of two other branches in the tree y>1 and z>1, how can I write the code?

**Comment by mayou36** [comment]
Hi, so zfit uses behind the scenes the [uproot](https://github.com/scikit-hep/uproot) packages and `root_dir_options` are directly forwarded to the open command. Depending on the uproot version, you can pass things through.

The more convenient way however would be to use the `uproot` package and create a pandas DataFrame, apply your cuts there (or when loading with uproot) and then load it into zfit as a dataframe

**Comment by XuelongQin** [comment]
Hi!
Thank you for your comment and I have solved the problem.
