### ISSUE TITLE
Version numbering is confusing at times

### ISSUE THREAD

**Issue by eduardo-rodrigues** [zfit/zfit#277]
Hi @mayou36, as I'm releasing a few scikit-hep metapackage versions and preparing a new one with partial Python 3.9 support I looked at dependencies .... and checked zfit after hepstats ... I got rather confused by the fact that you made a patch / bug fix release - the z in x.y.z - when you made zfit compatible with TF 2.3. That's not at all a patch release, right ;-)? May I suggest that for the future you make such upgrades more visible with a minor (y) update of version number?
(I would even go as far as suggesting that you remove 0.5.5 from PyPI and replace it with 0.6.0 ...)

 Thanks.

**Comment by mayou36** [comment]
This is an excellent remark, yes, you're complete right of course. I guess this somehow slipped that it was a breaking change, sorry for the troubles! And yes, that sounds like a good idea

**Comment by mayou36** [comment]
We made a new release with the new TF version, gonna be stricter about versions. Thanks again!

**Comment by eduardo-rodrigues** [comment]
Thanks @mayou36 👍 .
(For `scikit-hep` I even now made a note on versioning, see https://github.com/scikit-hep/scikit-hep#package-version-and-dependencies ... OK, that's different since a metapackage.)
