### ISSUE TITLE
Hyperlinks not rendered properly in the documentation of Parameter

### ISSUE THREAD

**Issue by tgag17** [zfit/zfit#307]
Some of the hyperlinks and class names in the documentation of Parameter(under Introduction) have not been rendered properly on the HTML page. 

For example: 
`
*For Jupyter notebooks, see also :ref:Parameters in Jupyter <parameters_in_jupyter>*
` 

 has been rendered as it is without the link.

**Comment by tgag17** [comment]
If possible I would be more than happy to make the necessary changes.

**Comment by mayou36** [comment]
Hi, many thanks for this, I've fixed it. It was a rather nasty thing with RST... If you ever want to make a fix directly, you're very welcome to do so by forking the repo, cloning and then making a PR.
