### ISSUE TITLE
Python versions to support

### ISSUE THREAD

**Issue by mayou36** [zfit/zfit#31]
So, for once the real question of Python 2.7 support: should we *really* still support it?

Arguments I recently discovered:
 * a lot of major libraries drop the support, e.g.:
   * [numpy won't release new features as of beginning of 2019, support ends beginning 202](https://docs.scipy.org/doc/numpy-1.14.1/neps/dropping-python2.7-proposal.html)
   * [matplotlib fully dropped support with the newest (3.0) release](https://github.com/matplotlib/matplotlib/releases/tag/v3.0.0)
   * [pandas will completely drop support beginning of 2019](https://www.analyticsvidhya.com/blog/2018/04/pandas-will-drop-all-support-for-python-2-next-year/)
   * [scikit-learn *has* already dropped 2.7 and 3.4 support in it's newest release](http://scikit-learn.org/dev/whats_new.html#changelog)
  * no one depends on the package with any code, so code written will be fresh, hence it should not be a problem at all to write it in Python 3+

The tide seems to be turning right now. How strong and what are the arguments for Python 2? (yes, legacy users... but given that *so many libraries* now drop support, I think there won't be a lot anymore)

My idea: drop 2.7 (and, if possible, 3.4 as well(to follow scikit-learn))

@apuignav your opinion?

**Comment by apuignav** [comment]
In general, I would say let's drop it, but I need to understand the status of python 3 in lxplus first. @rsilvaco, do you know it?

**Comment by apuignav** [comment]
Sooo, lxplus has python 3.4.8 by default. However, there are more versions available:

```shell
$ scl -l | grep python
python27
rh-python36
$scl enable rh-python36 bash
```

So I don't have any problems with dropping 2.7... 3.4, maybe not just yet? @rsilvaco what do you think?

**Comment by rsilvaco** [comment]
I think indeed makes not so much sense to keep these old versions. Indeed all the three analyses we are doing currently require even 2.7. In the Piz Daint I'm already using 3.4, so I don't see why we cannot base on Python 3+. As @mayou36 said, all the analyses anyway are going to be re-written, so let's just do it. My only concern is how much time this will require to migrate, because we want to release a version of the code at some point ....

**Comment by mayou36** [comment]
Albert wrote:
In general, I would say let's drop it, but I need to understand the status of python 3 in lxplus first. @rsilvaco, do you know it?

Albert wrote:
Sooo, lxplus has python 3.4.8 by default. However, there are more versions available:
```
$ scl -l | grep python
python27
rh-python36
$scl enable rh-python36 bash
```
So I don't have any problems with dropping 2.7... 3.4, maybe not just yet? @rsilvaco what do you think?

Rafael wrote:
I think indeed makes not so much sense to keep these old versions. Indeed all the three analyses we are doing currently require even 2.7. In the Piz Daint I'm already using 3.4, so I don't see why we cannot base on Python 3+. As @mayou36 said, all the analyses anyway are going to be re-written, so let's just do it. My only concern is how much time this will require to migrate, because we want to release a version of the code at some point ....

**Comment by apuignav** [comment]
So, our code is already 100% python3 compatible (let's say it's basically python3). But dropping 2.7 support will allow us to code a few things in a more straight-forward way and avoid jumping through certain hoops to keep backwards compatibility.

As I said, let's drop 2.7, 3.4 not just yet (although I would say this should be easy).

Albert

**Comment by mayou36** [comment]
@rsilvaco that sounds good, actually: the TensorFlowAnalysis that is currently used by Michele, Andrea *is* (AFAIK) already Python 3 compatible (I did some refactoring and things a while back), Michele is running his things currently under Python 3 (with 2-3 lines changed in his scripts). So I am optimistic about that.

Ok, let's drop 2.7 and keep 3.4 for the moment

**Comment by apuignav** [comment]
I don't think it matters. Our code is already 100% python 3 compatible.
It's just dropping explicit support for 2.7.

**Comment by hugovk** [comment]
See https://python3statement.org for a list of other projects that have pledged to drop support for Python 2.7 no later than 2020.

**Comment by mayou36** [comment]
@hugovk nice, thanks! Yep, that's an overwhelming majority, it's definitely the way to go.

**Comment by rsilvaco** [comment]
Thanks for the input @hugovk! We are looking forward for more comments from you in the future!

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #14](https://github.com/zfit/zfit-developement/issues/14) via [**ZenHub**](https://www.zenhub.com/)
