### ISSUE TITLE
Can we add the plot feature directly in the model?

### ISSUE THREAD

**Issue by coderpd** [zfit/zfit#312]
It will be good if we can plot the data directly by calling
model.plot(data, scale=1, plot_data=True)

For example in the introduction, if we want to plot the Gaussian pdf, we can call the plot function through 'gauss' obj
gauss.plot(data)

**Comment by tgag17** [comment]
Hi! According to me, this feature could go beyond the purpose of zfit as it is primarily developed to focus on model fitting and sampling. The plotting feature is required to visualize only the data along with the unfitted and/or fitted model on the data and could be useful to visualize the final result and get a concrete idea of it. But I believe that as zfit is mostly used as a helper tool to analyse the parameters and characteristics of the data, the plotting feature is an output of the general problem at hand and not the analysing part. Plus by using matplotlib separately, the user gets to access all the functions of it and keeps zfit light and flexible.

**Comment by mayou36** [comment]
Indeed, @tgag17 pretty much summarizes it why it should not go directly into zfit.

However, you do have a good (and often raised) point: that while this keeps it all flexible, it could also be nice to have helpers, something like `zfit.plot.plot1d(model, data=None, option...)` but that should rather go into a different package. We can maybe put a helper into zfit-physics, that could be an option. Are you interested @coderpd to contribute something like this (which is surely a larger thing to do)?

**Comment by coderpd** [comment]
yes, I am interested in contributing something like this. 
Zfit-physics seems good. We can make matplotlib an internal dependency of it. And then create these plotting APIs (with helpers as well).

**Comment by mayou36** [comment]
Hey, so I've started a discussion here: https://github.com/zfit/zfit-physics/discussions/10

Has some ideas, I've also added a `plot` namespace.
Let me know your thoughts

**Comment by mayou36** [comment]
@coderpd , feel free to close the issue here and continue the discussion in https://github.com/zfit/zfit-physics/discussions/10

**Comment by coderpd** [comment]
yea get it 👍
closing it here now
