### ISSUE TITLE
norm_range and space returns the same value. We can return the limits of space from norm_range.(It makes more sense)

### ISSUE THREAD

**Issue by coderpd** [zfit/zfit#313]
We can edit the norm_range property function in BasePDF class to return space.limits
norm_range is the normalization range, so returning limits looks good.
What does everyone say?

**Comment by mayou36** [comment]
Space and norm range are not exactly the same, they can differ. Also, it is basically already the limits that is returned, the returned space holds the limits actually. So this is intentionally "the same" for many cases.

But many thanks for bringing it up!
