### ISSUE TITLE
[misc] I'm working on fixing your pre-commit.ci run

### ISSUE THREAD

**Issue by asottile** [zfit/zfit#316]
👋 looks like the particular combination of hooks has tickled a bug in pre-commit.ci -- I'm currently debugging why that's happening and should have a fix for you soon!

**Comment by mayou36** [comment]
Interesting, thanks a lot

**Comment by asottile** [comment]
should be fixed now!  the root cause was a ruby hook with a `language_version` was causing the pre-commit.ci to have trouble computing disk utilization.  I fixed the permissions on that and now it should be smooth sailing!

I've requeued the 2 runs that were stuck so you should have results now for those (they'll display very large queue times because they were stuck in deadletter while I fixed the issue)

sorry for the inconvenience!

**Comment by mayou36** [comment]
No worries, that's software development, many thanks for the fast response!
