### ISSUE TITLE
Shifting the upcoming tutorials to a new space in the documentation

### ISSUE THREAD

**Issue by tgag17** [zfit/zfit#325]
The newly added/upcoming tutorials should be moved to a completely different section from the getting started section. I believe that as more tutorials will be added, the complexity of the same will increase and thus they will not fit in the current section which focuses more on the introductory concepts. 

By adding a new section:
- The users will be able to access it more efficiently as the new section would increase its visibility.
- Categorization of tutorials could be done more efficiently in the future on the basis of the usage of advanced concepts.

**Comment by mayou36** [comment]
That is indeed a good idea, we have already the tutorials at https://github.com/zfit/zfit-tutorials, and they were mostly added to have a visibility. However, this is indeed not the perfect structure.

Do you have a good idea for how to categorize them?

**Comment by tgag17** [comment]
I was thinking that we could categorize them on the basis of their complexity or a certain topic. Like we could have a subsection of basic usage followed by custom pdf/codes. After this, we could have a subsection on advanced topics like multidimensional pdfs and the toy study. I think the guides should have a separate section as they are different from the previously mentioned tutorials because they have more explanation. As of now, there are only 1-2 tutorials in each section so the categorization might seem a bit redundant but in my opinion, if more tutorials will be added in the future these could be really helpful. 

The basic flow:

Section: Tutorials

Sub Section: Basic usage
- Composite Models/ Tutorials on the inbuilt pdfs

Sub Section: Custom
- Custom codes/models
- Custom PDFs

Sub Section: Advanced Topics
- Multidimensional PDFs
- Toy Studies

 Sub Section: Tutorial Guides
- Combining measurements
- Models

**Comment by mayou36** [comment]
Hey, so I've set up something in #339, it's close to what you proposed but I also changed a few things. Have a look and let us know how you like it ;) And if you have an idea for improvements or dislike things, very welcome to hear
