### ISSUE TITLE
Conda releases for latest versions

### ISSUE THREAD

**Issue by eduardo-rodrigues** [zfit/zfit#347]
As seen in https://anaconda.org/conda-forge/zfit it turns out that the latest release available in Conda is 0.5.2. Could you provide the latest releases asap? I would actually like to use zfit 0.6 with the latest scikit-hep 3.2.0 on Python 3.9 for next week for a tutorial and got stuck.

Advance thanks!

**Comment by mayou36** [comment]
As discussed, unfortunately upstream dependencies don't have conda versions. But it's a good reminder, I'll try to convince them once again

**Comment by eduardo-rodrigues** [comment]
Yes, thanks. If that helps you can cite our 2 Scikit-HEP and zfit orgs with quite a large user base by now ...
