### ISSUE TITLE
`functional` module

### ISSUE THREAD

**Issue by mayou36** [zfit/zfit#36]
I can think of three level of uses of the repo:

 1. high-level: pdf.fit_to(data, range)
 2. normal level: construct your own things *using the repository fully*, e.g. construct a likelihood with `unbinned_nll(pdf, data, range)`
 3. functional level: using a *minimum of the repository*, e.g. unbinned_nll(probs, normalization, yields, data,...) (as it was originally in the TensorFlowAnalysis)

Why this split up in the second and third: the second is (using the `pdf` classes) the same as the third but way easier and should therefore be there. The third one allows for very easy access and works as "*just some tools to build your own fit*".

I'd say, 3. does not have priority. But if an implementation is straight forward to split it like this (and 2. acting just as a wrapper for 3.), then we should do it in this way and provide the functional approach (3.) in the `zfit.functional` namespace (or other name).

Opinions?

**Comment by apuignav** [comment]
It's an interesting idea, but it may create too much indirection? Can we do it in an easy way that's simple to follow if you're using 2 and you want to understand what is going on?

**Comment by mayou36** [comment]
Could be, I agree. So I'd propose to add it and if there is something that *anyway* is "purely" functional, we put it there. So for the "just-in-case" which fits perfectly. And if there is some real need later on, we can refactor. ok?
