### ISSUE TITLE
MinimizerState - API and specs

### ISSUE THREAD

**Issue by mayou36** [zfit/zfit#37]
## specs
- dumpable at some point?
- difference to Minimizer: stores everything in evaluated (numpy, python...) format -> only defined **after** a fit has been performed.

## API

- parameters (how? limits?)
  - **different to minimizer**: stored as python objects, not Tensors
- edm -> Estimated Distance to Minimum
- fmin -> minimum of function
- status (can be a complex object if the minimization process is complex)

**Comment by apuignav** [comment]
I guess all the state from the minimizer

- parameters -> getter/setters to access the variables, not sure how though
- edm -> Estimated Distance to Minimum
- fmin -> minimum of function
- status (can be a complex object if the minimization process is complex)

**Comment by apuignav** [comment]
Rename to `MinimizerState`.

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #8](https://github.com/zfit/zfit-developement/issues/8) via [**ZenHub**](https://www.zenhub.com/)
