### ISSUE TITLE
Python 3.10 and TF 2.7+

### ISSUE THREAD

**Issue by jonas-eschle** [zfit/zfit#397]
Upgrade to the new Python version and TF versions.

This is currently restricted possible only because of failures with the gradient that seem to stem from a different handling of parameters (tf.Variables)

Currently WIP by @jonas-eschle

**Comment by henryiii** [comment]
This is keeping the Scikit-HEP tutorial from upgrading to Python 3.10! Any chance the restriction can be relaxed yet? 3.10 came out 10 months ago at this point.

**Comment by jonas-eschle** [comment]
Yes, that's on my list, I am actually working on it right now. The issue is with some internal changes of dependencies that required quite some working around, but it should be out within this week actually (just got pinged by someone else too)

**Comment by jonas-eschle** [comment]
@henryiii we merged now #372, so zfit is compatible with Python 3.10! I will make a release in the next few days, but installing from dev should already work

**Comment by jonas-eschle** [comment]
@henryiii 0.10.0 is out and fully compatible with Python 3.10, closing
