### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by apuignav** [zfit/zfit#41]
We need to think about documentation, and I like a lot how [lmfit](https://lmfit.github.io/lmfit-py/) does it. Following how they do it, I would propose the following structure:

- Getting started (a sort of simple introduction on how to do a few basic things).
- Download, install, setup
- Specific core topics, which mix explanations with (autogenerated) code documentation, only discussing public functions, with a final example putting things in perspective. These topics should include
  + Parameters
  + General information about PDFs
  + Fitting
  + Generating
- Advanced mode: how to use, use cases, etc... Playing a bit with tensorflow.
- A detailed list of all the included PDFs

All of these could include links to tutorials in https://github.com/zfit/zfit-tutorials, possible with a (mybinder)[https://mybinder.org/] to execute them directly. In fact, the examples could directly be embedded tutorials.

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #23](https://github.com/zfit/zfit-developement/issues/23) via [**ZenHub**](https://www.zenhub.com/)
