### ISSUE TITLE
Bug in zfit.constraint.SimpleConstraint ?

### ISSUE THREAD

**Issue by P-H-Wagner** [zfit/zfit#442]
**Bugs**

I get an error when I try to implement an easy, user defined constraint with zfit.constraint.SimpleConstraint. As an exercise, I tried to implement the example, which was given in an old documentation of zfit (https://zfit.readthedocs.io/en/0.5.6/getting_started/intro/loss.html?highlight=tutorial%20constraints#adding-constraints), see below.

## Current Behaviour

I define my custom constraint:
```
def custom_constraint(param):
        max_value = 100
        return tf.cond(tf.greater_equal(param, max_value), lambda: 1000000., lambda: 0.)
```
and I add it to the loss:
```
simple_constraint = zfit.constraint.SimpleConstraint(custom_constraint, params=Nc)
my_loss.add_constraints(simple_constraint)
```
The only difference to your example is that my parameter (Nc) is the background yield of an ExtendedBinnedSumPDF, thus my loss is an ExtendedBinnedNLL,  and I changed the condition to something silly, to see if the constraint has really an effect. In my case, if Nc is bigger than max_value = 100, which it is very clearly (we have around 100k events), I drive it away from the loss by returning 1000000.
The minimization works fine without this constraint. But after adding this constraint to the loss, I get the following error message:

  File "fitscale.py", line 454, in minimizer
    result = minimizer.minimize(nll)
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/minimizers/baseminimizer.py", line 500, in minimize
    return self._call_minimize(loss=loss, params=params, init=init)
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/minimizers/baseminimizer.py", line 512, in _call_minimize
    result = self._minimize(loss=loss, params=params, init=init)
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/minimizers/baseminimizer.py", line 92, in new_func
    return func(*args, **kwargs)
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/minimizers/minimizer_minuit.py", line 195, in _minimize
    minimizer = minimizer.migrad(**minimize_options)
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/iminuit/minuit.py", line 694, in migrad
    fm = migrad(ncall, self._tolerance)
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/minimizers/evaluation.py", line 246, in value
    loss_value = self.loss.value()
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/core/loss.py", line 428, in value
    value = self._call_value(
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/core/loss.py", line 434, in _call_value
    value = self._value(
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/core/loss.py", line 450, in _value
    return self._loss_func(
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/z/zextension.py", line 296, in concrete_func
    result = func_to_run(*args, **kwargs)
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/_loss/binnedloss.py", line 316, in _loss_func
    [c.value() - log_offset * len(c.get_params()) for c in constraints]
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/_loss/binnedloss.py", line 316, in <listcomp>
    [c.value() - log_offset * len(c.get_params()) for c in constraints]
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/core/constraint.py", line 45, in value
    return self._value()
  File "/work/pahwagne/environments/master5/lib/python3.8/site-packages/zfit/core/constraint.py", line 76, in _value
    return self._simple_func()
TypeError: custom_constraint() missing 1 required positional argument: 'param'
(/work/pahwagne/environments/master5) [pahwagne@t3wn60 bigsamples]$ 

## Expected Behaviour

The fitter should try to clamp the value of Nc below 100 ( where in truth we have around 100k events) and thus give me a very wrong result with bad errors, or not even find a minimum. But it fails already earlier at:
TypeError: custom_constraint() missing 1 required positional argument: 'param'

## Context (Environment)

- zfit version: 0.11.1 
- Python version: 3.8.16
- Are you using conda, pipenv, etc? : I use a conda environment to which I installed zfit with pip in order to have the newest version
- Operating System: Linux
- Tensorflow version: 2.11.0 

## Possible Solution/Implementation

By looking at the error message and the source code of the class in constraint.py line :

```
class SimpleConstraint(BaseConstraint):
    def __init__(self, func: Callable, params: ztyping.ParameterType | None):
        """Constraint from a (function returning a) Tensor.

        The parameters are named "param_{i}" with i starting from 0 and corresponding to the index of params.

        Args:
            func: Callable that constructs the constraint and returns a tensor.
            params: The dependents (independent ``zfit.Parameter``) of the loss. If not given, the
                dependents are figured out automatically.
        """
        self._simple_func = func
        self._simple_func_dependents = convert_to_container(
            params, container=OrderedSet
        )

        params = convert_to_container(params, container=list)
        params = OrderedDict((f"param_{i}", p) for i, p in enumerate(params))

        super().__init__(name="SimpleConstraint", params=params)

    def _value(self):
        return self._simple_func()
```
The custom_constraint gets called in _value() by self._simple_func() but with no argument. But we defined custom_constraint with the argument "param". I think I fixed it by changing a few lines:

```
class SimpleConstraint(BaseConstraint):
     def __init__(self, func: Callable, params: ztyping.ParameterType | None):
         """Constraint from a (function returning a) Tensor.
 
         The parameters are named "param_{i}" with i starting from 0 and corresponding to the index     of params.
 
         Args:
             func: Callable that constructs the constraint and returns a tensor.
             params: The dependents (independent ``zfit.Parameter``) of the loss. If not given, the
                 dependents are figured out automatically.
         """
         self._simple_func = func(params)        #CHANGED !!!
         self._simple_func_dependents = convert_to_container(
             params, container=OrderedSet
         )
 
  
         params = convert_to_container(params, container=list)
         params = OrderedDict((f"param_{i}", p) for i, p in enumerate(params))
 
         super().__init__(name="SimpleConstraint", params=params)
 
     def _value(self):
         return self._simple_func        #CHANGED !!!
```

Like this I get rid of the error and the zfit.constraint.SimpleConstraint now returns an OrderedDict with a value. 
The program terminates again, but it still seems to completely ignore my constraint and reproduces the same result as without constraint. I checked that tf.greater_equal returns True (since Nc > 100) and in turn tf.cond returns the 1000000. I also converted this number into a tf.Tensor object, by returning lambda: tf.convert_to_tensor(1000000, type = np.float64) in my custom _constraint. This did not help, the minimization seems to stay unaffected.

I don't know if my change of code attacks the problem correctly, it would be nice if anyone could have a look at the SimpleConstraint, thank you already in advance!

**Comment by jonas-eschle** [comment]
Thanks for bringing this up! The function is simply expected not to take any arguments (but that comes from an older philosophy with TensorFlow).
I've implemented the changes in #444, should be fixed with the new release
