### ISSUE TITLE
Typo on DoubleCB documentation

### ISSUE THREAD

**Issue by Tristan63170** [zfit/zfit#468]
Hello, I think that there is a typo on the DoubleCB documentation web page. Concerning the right handed part solution if think you have to change one sign (see ROOT documentation https://root.cern.ch/doc/master/classRooCrystalBall.html ):
$A_{R} \\cdot (B_{R} - \\frac{x - \\mu}{\\sigma})^{-n_R}$ must be $A_{R} \\cdot (B_{R} + \\frac{x - \\mu}{\\sigma})^{-n_R}$.

**Comment by jonas-eschle** [comment]
Hi Tristan, thanks for bringing this up, this looks like a typo to me, indeed! Would you be up to make a quick PR and fix this if you know how to do that? I can guide you if you want

**Comment by iasonkrom** [comment]
@jonas-eschle This can be closed
