### ISSUE TITLE
[QUESTION] repr of ProdPDF reports no params

### ISSUE THREAD

**Issue by tomeichlersmith** [zfit/zfit#491]
I'm working through the zfit tutorials and I got stuck when playing with the[ Composite Models](https://github.com/zfit/zfit-tutorials/blob/master/components/20%20-%20Composite%20Models.ipynb) example.

Leaving the notebook unchanged, I ran the cells to get `prod_gauss` defined and then evaluated a cell with it to see its repr.
```
prod_gauss
# result:
<zfit.<class 'zfit.models.functor.ProductPDF'>  params=[]
```
This caused me some confusion. I expected `params` to contain the parameters from the PDFs used to create `prod_gauss`, i.e. I expected
```
prod_gauss
# result:
<zfit.<class 'zfit.models.functor.ProductPDF'>  params=[mu1, sigma1, mu3, sigma3]
```
since
```
gauss1, gauss3
# result:
(<zfit.<class 'zfit.models.dist_tfp.Gauss'>  params=[mu1, sigma1],
 <zfit.<class 'zfit.models.dist_tfp.Gauss'>  params=[mu3, sigma3])
```
Is there something wrong with my understanding of ProdPDF? Is there a bug in the example notebook? Does the ProdPDF `__repr__` need to be patched?

To be clear, I think this is just an issue with the repr since I was able to follow up with fitting 2D unbinned data with this ProdPDF successfully, but the lack of `params` in the repr did give me a scare.

**Comment by tomeichlersmith** [comment]
For clarity, this is what I see when I create some 2D data and fit `prod_gauss` to it. I put each cell with a `>>> ` prompt and then show its output inline. The warning upon creation of `nll` is a bit concerning but I suspect that's just due to me using a malformed `data` or `prod_gauss` object.

```
>>> data_np = np.random.normal(size=(10_000, 10_000), scale=2)
>>> data = zfit.Data.from_numpy(obs=prod_gauss.obs, array=data_np)
>>> nll = zfit.loss.UnbinnedNLL(prod_gauss, data)
/home/tom/code/zfit/venv/lib/python3.10/site-packages/zfit/core/loss.py:296: AdvancedFeatureWarning: Either you're using an advanced feature OR causing unwanted behavior. To turn this warning off, use `zfit.settings.advanced_warnings['inconsistent_fitrange'] = False`  or 'all' (use with care) with `zfit.settings.advanced_warnings['all'] = False
PDFs [<zfit.<class 'zfit.models.functor.ProductPDF'>  params=[]] as well as `data` [<zfit.core.data.Data object at 0x7fed32333df0>] have different ranges [(<zfit Space obs=('obs1', 'obs2'), axes=(0, 1), limits=(array([[-5., -3.]]), array([[5., 7.]])), binned=False>, <zfit Space obs=('obs1', 'obs2'), axes=(0, 1), limits=None, binned=False>)] they are defined in. The data range will cut the data while the norm range defines the normalization.
  warn_advanced_feature(
>>> nll.get_params()
OrderedSet([<zfit.Parameter 'mu1' floating=True value=1>, <zfit.Parameter 'sigma1' floating=True value=1>, <zfit.Parameter 'mu3' floating=True value=1>, <zfit.Parameter 'sigma3' floating=True value=1>])
>>> minimizer = zfit.minimize.Minuit()
>>> minimizer.minimize(nll)
FitResult of
<UnbinnedNLL model=[<zfit.<class 'zfit.models.functor.ProductPDF'>  params=[]] data=[<zfit.core.data.Data object at 0x7fed32333df0>] constraints=[]> 
with
<Minuit Minuit tol=0.001>

╒═════════╤═════════════╤══════════════════╤═════════╤═════════════╕
│ valid   │ converged   │ param at limit   │ edm     │ min value   │
╞═════════╪═════════════╪══════════════════╪═════════╪═════════════╡
│ True    │ True        │ False            │ 4.2e-06 │ -18069.34   │
╘═════════╧═════════════╧══════════════════╧═════════╧═════════════╛

Parameters
name      value  (rounded)    at limit
------  ------------------  ----------
mu1             -0.0392847       False
sigma1             2.17351       False
mu3               -1.20777       False
sigma3             2.79272       False
```

**Comment by jonas-eschle** [comment]
Hi, thanks for the question and the expected display, you're right, it has only to do with the repr. 

There are two kinds of "parameters" in this sense: the parameters that the PDF _explicitly_ depends on and the parameters that it _implicitly_, through it's children, depends on.
Mathematically, you're correct, it's all the parameters (implicit and explicit). The question is, what should be displayed best in the repr? As it can grow quickly, if you sum a lot of PDFs, so far we decided to only show the explicit parameters of the pdf.

In zfit PDFs, they are both accesible: `pdf.params` is the dict that holds the explicit params, a dictionary matching the name of the parametrization with the actual variable; a Gaussian has "mu" and "sigma" keys, the values are a parameter (this can be a composedParameter, it can be the same parameter, all possible)
`pdf.get_params(...)` is a function to obtain the dependent params, i.e. all params that the pdf depends on (it has a few arguments to filter them meaningfully, i.e. whether to get yields (only, as well, not) etc. This is an unsorted container.
`get_params` is used wherever this is relevant, i.e. the minimizer takes by default all params, that's achieved with `get_params` (likelihoods also have this method).

The question is, what is sensible to be displayed. `params` allows for a nice display, i.e. of a Gaussian (params: mu=mypar1, sigma=mypar2) but a product falls short of something nice (a SumPDF is a good example of having explicit, the fractions, and implicit params btw).
This is open for discussions, if you have a good idea or a strong argument for one or the other, glad to hear that.

Technically, it's a trivial change, it's just about the design.

**Comment by tomeichlersmith** [comment]
That makes sense - thank you for the extra explanation! I think the current choice is a good one now that I know the context.
