### ISSUE TITLE
Fitting one function over more than one range

### ISSUE THREAD

**Issue by becci-is-a-unicorn** [zfit/zfit#492]
Hi,

I am currently trying to fit an exponential over my background data. Since I cut out the signal region, my background data is in two ranges. I would like to make a fit using both of the ranges. 

I tried

1) to define the fit function only in the areas that I want to fit
```
obs1 = zfit.Space('m1', limits=(4,  mass_lower_threshold))
obs2 = zfit.Space('m2', limits=(mass_higher_threshold, 7))
obs_sum = zfit.dimension.combine_spaces(obs1, obs2)

exp1 = zfit.pdf.Exponential(lam=lambda_real ,obs=obs_sum,  extended=None, norm=None, `name='exp1')
```
but this gives me the error
`SpaceIncompatibleError: Exactly 1 obs are allowed, ('m1', 'm2') are given.`

and

2) giving a fit range in the UnbinnedNLL
`loss = zfit.loss.UnbinnedNLL(exp, data, fit_range=([4, mass_lower_threshold], [mass_higher_threshold, 7]))`
which gives the error
`ShapeIncompatibleError: Inferred last dimension (2) does not coincide with given n_obs (1)`

I don't see another way of how to do this. If there is one, please let me know. If there is none, I think this would be a useful feature to implement in the future.
![bkg_region](https://github.com/zfit/zfit/assets/56561132/75889708-fce9-467a-945c-03da2674c5f3)

Thanks in advance.
Rebecca

**Comment by jonas-eschle** [comment]
Hi Rebecca, the function that you're looking for is probably `add_spaces`, not `combine`. You can also just add them with the `+` operator

```
space = space1 + space2
```

The `combine` (alternatively with the product `*` operator) creates a multidimensional space

**Comment by jonas-eschle** [comment]
Hi @becci-is-a-unicorn , as I didn't hear back from you, could you implement the suggestion? Does that work?

**Comment by becci-is-a-unicorn** [comment]
Hi @jonas-eschle ,

I worked around the issue by using RooFit, so I forgot about this issue. But no, your suggestions don't work for me.

When I do 

`obs1 = zfit.Space('m1', limits=(4,  5))`
`obs2 = zfit.Space('m2', limits=(5.5, 7))`
`obs_sum = zfit.dimension.add_spaces(obs1, obs2)
`
or 

`obs1 = zfit.Space('m1', limits=(4,  5))`
`obs2 = zfit.Space('m2', limits=(5.5, 7))`
`obs_sum = obs1 + obs2`

I get the error
`ObsIncompatibleError: The requested obs ('m1',) are not compatible with the current obs ('m2',)`

**Comment by jonas-eschle** [comment]
Ah sorry, I've been too fast and overlooked something in the code: the observables need to be in the same variable. The objects can hold different limits, i.e.
```
obs1 = zfit.Space('m1', limits=(4,  mass_lower_threshold))
obs2 = zfit.Space('m1', limits=(mass_higher_threshold, 7))
obs_sum = obs1 + obs2

exp1 = zfit.pdf.Exponential(lam=lambda_real ,obs=obs_sum,  extended=None, norm=None, `name='exp1')
```
and create the data with the same `obs_sum`, no `fit_range` argument is then needed as well.

Does that work?

**Comment by becci-is-a-unicorn** [comment]
Yes, that works. Thank you!
