### ISSUE TITLE
Incorrect BinnedData axis binning when using an axis transform

### ISSUE THREAD

**Issue by mpoehlmann** [zfit/zfit#504]
I'm creating a `BinnedData` from a histogram which has an axis with a log transform. The binning of the data doesn't match that of the histogram. Here is an example.
```python
import hist
import zfit

h = hist.Hist(hist.axis.Regular(30, 1e-2, 1e1, transform=hist.axis.transform.log, name="x"))
print(h.axes[0].edges)
data = zfit.data.BinnedData.from_hist(h)
print(data.space.binning[0].edges)
```
The first print statement gives `[ 0.01        0.01258925  0.01584893  0.01995262  0.02511886  0.03162278  0.03981072  0.05011872  0.06309573  0.07943282  0.1         0.12589254  0.15848932  0.19952623  0.25118864  0.31622777  0.39810717  0.50118723  0.63095734  0.79432823  1.          1.25892541  1.58489319  1.99526231  2.51188643  3.16227766  3.98107171  5.01187234  6.30957344  7.94328235 10.        ]`
while the second gives `[ 0.01   0.343  0.676  1.009  1.342  1.675  2.008  2.341  2.674  3.007  3.34   3.673  4.006  4.339  4.672  5.005  5.338  5.671  6.004  6.337  6.67   7.003  7.336  7.669  8.002  8.335  8.668  9.001  9.334  9.667 10.   ]`

I'm using zfit 0.16.0. Thanks for looking into this!

**Comment by jonas-eschle** [comment]
Hm, I need to dig a bit deeper here, transformations are "ignored" in zfit, but my understanding was that this doesn't change the edges. Seemingly, there is an error in the transformation

**Comment by mpoehlmann** [comment]
I only ran into this issue when plotting post-fit histograms. I can fix this on my end if I convert the initial histogram axis to use a variable binning:
```python
ax1 = hist.axis.Regular(30, 1e-2, 1e1, transform=hist.axis.transform.log, name="x")
ax2 = hist.axis.Variable(ax1.edges, name="x")
```

For the time being, you could add a flag [here](https://github.com/zfit/zfit/blob/ec44912bebac52ef5e404c29cac8c37c37554e4d/zfit/_variables/axis.py#L105) that throws an error if the axis has a transform defined (`if axis.transform is not None`)

**Comment by jonas-eschle** [comment]
Sorry for the late response, I thought I had answered already: I agree, the exception may the the most feasible way to go about it. Alternatively, we could just transform it into a variable axis, but that is maybe confusing

Do you want to add this? Please go ahead, I'll gladly review the PR or assist if anything is needed

**Comment by jonas-eschle** [comment]
Hi @mpoehlmann , would you be up to add the fix?
