### ISSUE TITLE
Piecewise pdf did not work well

### ISSUE THREAD

**Issue by Lowerce** [zfit/zfit#526]
When a Piecewise pdf was defined, **sample** related method did not work.
## Current Behaviour

```
class Bug(zfit.pdf.ZPDF):
    _N_OBS = 1  # dimension, can be omitted
    _PARAMS = ['alpha', 'beta', 'E']  # the name of the parameters
    
    def _unnormalized_pdf(self, x):
        x = z.unstack_x(x)  # returns a list with the columns: do x, y, z = z.unstack_x(x) for 3D
        alpha = self.params['alpha']
        beta = self.params['beta']
        E = self.params['E']
        return tf.cond(tf.less(x,((alpha-beta)*E/(2+alpha))) , lambda: ((x/100)**alpha)*z.exp(-x*(2+alpha)/E), lambda: ((((alpha-beta)*E/(100*(2+alpha)))**(alpha-beta))*z.exp(beta-alpha)*((x/100)**beta)))

obs = zfit.Space('x', (50, 300))
alpha = zfit.Parameter('alpha', -1.9)
beta = zfit.Parameter('beta', -3.7)
E = zfit.Parameter('E', 70)
model = Bug(obs=obs, alpha=alpha, beta=beta, E=E)

sampler = model.create_sampler(n=3000, fixed_params=True)
sampler.resample()
```

After running above code, output as follows:
```
The second input must be a scalar, but it has shape [6060]
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/while/body/_24/while/StatefulPartitionedCall/cond/else/_203/cond/StatefulPartitionedCall/cond/Func/StatefulPartitionedCall/StatefulPartitionedCall/while/body/_24/while/StatefulPartitionedCall/cond/else/_203/cond/StatefulPartitionedCall/input/_350/_465}}]] [Op:__inference__create_sampler_tensor_2005]
```

## Expected Behaviour
Work well.

## Context (Environment)

- zfit version:0.16.0
- Python version:3.11.6
- Are you using conda, pipenv, etc? :venv
- Operating System:MacOS
- Tensorflow version:2.13.1

**Comment by anjabeck** [comment]
Hi @Lowerce 

if you change `tf.cond()` to `tf.where()` it works (see code below).

I believe the reason is that zfit expects a scalar as the output of `Bug.pdf()` but `tf.cond()` returns a function. `tf.where()` on the other hand returns an array of scalars. This is not really a bug in zfit but rather a (necessary?) choice made at implementation.

```python
import zfit
import tensorflow as tf
import zfit.z.numpy as z

class Bug(zfit.pdf.ZPDF):
    _N_OBS = 1  # dimension, can be omitted
    _PARAMS = ['alpha', 'beta', 'E']  # the name of the parameters
    
    def _unnormalized_pdf(self, x):
        x = x.unstack_x(x)  # returns a list with the columns: do x, y, z = z.unstack_x(x) for 3D
        alpha = self.params['alpha']
        beta = self.params['beta']
        E = self.params['E']
        condition = tf.less(x, ((alpha-beta)*E/(2+alpha)))
        truth = ((x/100)**alpha)*z.exp(-x*(2+alpha)/E)
        wrong = ((((alpha-beta)*E/(100*(2+alpha)))**(alpha-beta))*z.exp(beta-alpha)*((x/100)**beta))
        return tf.where(condition, truth, wrong)

obs = zfit.Space('x', (50, 300))
alpha = zfit.Parameter('alpha', -1.9)
beta = zfit.Parameter('beta', -3.7)
E = zfit.Parameter('E', 70)
model = Bug(obs=obs, alpha=alpha, beta=beta, E=E)

sampler = model.create_sampler(n=3000, fixed_params=True)
sampler.resample()
```
(I tested this with a slightly more modern version of `tensorflow` than you say but that shouldn't matter)

**Comment by Lowerce** [comment]
Thanks a lot for your reply.
Your solution did solve my problem!
Some tensor related behaviors were unfamiliar to me, maybe more knowledge about it was needed for using zfit.
I will close this issue and I hope zfit will be better in the future.
Thanks again!

**Comment by jonas-eschle** [comment]
@Lowerce to expand on the above: Tensors are like numpy arrays, they are vectors, and the methods that you would use for numpy arrays should be used for tensors too (they're basically the same thing).

tf.cond is special and represents an "if" statement in a compiled environment, it's _not_ the same as where-> in numpy, you would do `np.where(bool, trueval, falseval)`, here you can do `znp.where` (or `tf.where`, it's the same)

As a rule of thumb: if you use what is in np (i.e. np.where, np.max) and directly use `znp` (that is, `import zfit.z.numpy as znp`), things should work out of the box. You can also use `tf.`, it's the same, just another name. If you need _more, anything like `tf.cond`, `tf.while` etc, you most likely don't want to do that, it's quite advanced. It is special and does not occur in numpy: it means, it's logix that depends on scalars and replaces `if` or `while` in Python (and they should be avoided if possible, as, generally in Python, vectorized computations are a lot more efficient).

For more information about the `tf.cond` etc (although, as said, you most like won't need it, but for interest and advanced usecases), but also just about tensors and that they are the same as np arrays: https://zfit-tutorials.readthedocs.io/en/latest/tutorials/TensorFlow/HPC_with_TensorFlow.html

Hope this helps to better understand the issue

**Comment by Lowerce** [comment]
Thanks a lot for your patient explanation. Learned a lot from your advice and tips in using zfit.
