### ISSUE TITLE
Pydantic dependency

### ISSUE THREAD

**Issue by andresailer** [zfit/zfit#564]
Hi @jonas-eschle 

Is the requirement for pydantic something for the runtime of zfit

https://github.com/zfit/zfit/blob/7a2fc4d9401bc1c83da32971b6a65e3aa49dbaca/requirements.txt#L17

Or is this a testing dependency?
For the LCGstacks it would be nice if we can update pydantic.

Thanks for clarifying!

**Comment by jonas-eschle** [comment]
Hey thanks, it's unfortunately a runtime dependency, but an inconvenient one! It is however only used in the serialization.
We're working on getting it upgraded or at least having it as an optional dependency, it's a blocker otherwise.
I'll ping you if there are updates

**Comment by andresailer** [comment]
Thanks for your answer! I look forward to the update :)
We are currently trying to get python 3.11 integrated, and for that we need to update pydantic.

**Comment by jonas-eschle** [comment]
> We are currently trying to get python 3.11 integrated, and for that we need to update pydantic.

Out of curiosity, why exactly would you need that for Python 3.11? I assume some dependency conflicts? Pydantic 1 supports up to 3.12 at least

**Comment by andresailer** [comment]
Ahh, good point! Maybe we just too eagerly updated from the version we had, and we should just go to https://pypi.org/project/pydantic/1.10.15/.

**Comment by jonas-eschle** [comment]
That should surely work as an intermediate step, yes

I'll keep this anyway open, as we're trying to move to Pydantic 2 anyways

**Comment by ikrommyd** [comment]
@andresailer you will need pydantic 2 if you upgrade `correctionlib` to v2.5.0 though.

**Comment by ikrommyd** [comment]
@jonas-eschle with the [correctionlib 2.6.0 release[(https://github.com/cms-nanoAOD/correctionlib/releases/tag/v2.6.0) which contained a critical fix for numpy 2, correctionlib depending on pydatic 2 and coffea requiring correctionlib>=2.6.0, it's very important for LCG releases that zfit either upgrades to pydantic 2 or makes pydantic optional. I think the second option is the what is easier and quicker to do and we'll just not be able to serialize if pydantic 1 is not installed.

**Comment by jonas-eschle** [comment]
Agree, let's make it optional at least, thanks!

**Comment by jonas-eschle** [comment]
@andresailer this was fixed, a new release should be out in the next days/weeks, so Pydantic 2 is fine with us

**Comment by andresailer** [comment]
Great! I'll put the new release in as soon as it is out!

**Comment by andresailer** [comment]
Hi @jonas-eschle ,
Do you have an estimate when a new zfit release will happen? There will be a new LCG release very soon.
Thanks!

**Comment by jonas-eschle** [comment]
@andresailer What's the intended supported TF version in the new LCG release? I thought to wait for 2.17, but [TensorFlow-Probability](https://github.com/tensorflow/probability/issues/1832) didn't upgrade yet.

If you don't mind this, and TF 2.16 as a dep is fine, I'll do the release nowish

**Comment by andresailer** [comment]
No plan to update tensorflow at this point, so going with TF 2.16.

**Comment by jonas-eschle** [comment]
@andresailer it's published on pypi, 0.22.0
