### ISSUE TITLE
Update of composed Parameter not working in new zFit versions

### ISSUE THREAD

**Issue by otittel** [zfit/zfit#582]
I perform a fit in which I have composed parameter which is calculated using the tensorflow function einsum. When performing the fit, this parameter does not update when the values on which it depends are changing. The issue is observed with zFit version 0.22.0 and TF version: 2.16.2. Testing the same code with zFit version 0.17.0 and TF version: 2.13.1 does not result in this problem.

## Current Behaviour

Below is a minimal example in which I define the composed Parameter, evaluate it, change one of the Parameters it depends on and evaluate again. I run the code in a notebook, so I can execute the code in steps as described below. This part is in zFit version 0.22.0 and TF version: 2.16.2.

```
import zfit
import tensorflow as tf

a = zfit.Parameter('a', 5 , -1000, 1000)
b = zfit.Parameter('b', 5, -1000, 1000)
c = zfit.Parameter('c', 5 , -1000, 1000)
d = zfit.Parameter('d', 5, -1000, 1000)

def einsum(la, lb):
    return tf.einsum('i,j->', tf.convert_to_tensor(la), tf.convert_to_tensor(lb))

test = zfit.ComposedParameter('test', einsum, params=[[a, b], [c, d]])
test
```
gives

```
<zfit.ComposedParameter 'test' params=[('param_0', 'FIXED_autoparam_0'), ('param_1', 'FIXED_autoparam_1')] value=100>
```

now setting a new value for `a` and reevaluating

```
a.set_value(15)
test
```

also gives

```
<zfit.ComposedParameter 'test' params=[('param_0', 'FIXED_autoparam_0'), ('param_1', 'FIXED_autoparam_1')] value=100>
```

Now, running the same code with zFit version 0.17.0 and TF version: 2.13.1 behaves the same, except for the last output, which is

```
<zfit.ComposedParameter 'test' params=[('param_0', 'FIXED_autoparam_0'), ('param_1', 'FIXED_autoparam_1')] value=200>
```

## Expected Behaviour

The composed parameter should update even when using non trivial TF functions. The updates work fine in both version when using a simple sum like 

```
def plus_func(a, b):
    return a+b

test = zfit.ComposedParameter('test', plus_func, params=[a, b])
```

## Context (Environment)

- zfit version: 0.22.0
- Python version: 3.9.18
- Are you using conda, pipenv, etc? : venv
- Operating System: RedHat 9.3
- Tensorflow version: 2.16.2

**Comment by jonas-eschle** [comment]
Hi @otittel , thanks for reporting the issue nicely, made it easy for me to reproduce.

The issue doesn't seem to be with the content of the function but with how the parameters are given: they shouldbe a list or a dict of parameters (and if that's not the case, it should be caught and error, which it doesn't in your example). Therefore, it converts the first list of two parameters to a static value.

I've rewritten your example how it could work (note also the `unpack_params` which doesn't change anything but makes it more explicit that you're not expecting a single argument in the function.
```
import zfit
import tensorflow as tf

a = zfit.Parameter('a', 5 , -1000, 1000)
b = zfit.Parameter('b', 5, -1000, 1000)
c = zfit.Parameter('c', 5 , -1000, 1000)
d = zfit.Parameter('d', 5, -1000, 1000)

import zfit.z.numpy as znp

def einsum(la1, la2, lb1, lb2):
    return tf.einsum('i,j->', znp.asarray((la1, la2)), znp.asarray((lb1, lb2)))

test = zfit.ComposedParameter('test', einsum, params=[a, b, c, d], unpack_params=True)

print(test)
b.set_value(15)
print(test)
```

You could also provide a dict with names to make sure each parameter.

This seems to work for me, does it also work for you?

**Comment by otittel** [comment]
Hi @jonas-eschle 
Thank you for the fast reply. Your solution works for me. However, it is not what I want to do. In my fit, the length of the lists which go into the einsum function are variable, so I can not pre-define all parameters. I actually want to pass a list as the argument. Is there a way to do this?
Also, why is the behavior different in the older zFit version?

**Comment by jonas-eschle** [comment]
Ah, yes, what you want is even easier: just use a single argument, and ideally, name it `params`. That's also the intended way to use it.
```
def workaround(params):
    # do something
    return ...


test = zfit.ComposedParameter('test', workaround, params=[a, b, c, d])
```

Where did you find the example of using each argument as a parameter btw? This is "still possible", but discouraged.


If you wanna have another argument, I would suggest to use `partial`, that's the safest way. So the following works best if, i.e., the additional argument is a power.
```
a = zfit.Parameter('a', 1)
b = zfit.Parameter('b', 12)
c = zfit.Parameter('c', 13)
d = zfit.Parameter('d', 14)


def workaround_pow(params, pow):
    half = int((len(params) / 2))
    couplings = tf.convert_to_tensor(params[:half])
    couplings_bar = tf.convert_to_tensor(params[half:])

    return tf.einsum('i,j->', couplings, couplings_bar) ** pow


workaround = functools.partial(workaround_pow, pow=2)

test = zfit.ComposedParameter('test', workaround, params=[a, b, c, d])
```

Does that work?

**Comment by jonas-eschle** [comment]
Hi @otittel , can you confirm that this works in the proposed way and close the issue if it does?

**Comment by otittel** [comment]
Hi @jonas-eschle , yes, sorry. Your solution works. Thank you very much!
