### ISSUE TITLE
Add a `hist` method to PDFs

### ISSUE THREAD

**Issue by apuignav** [zfit/zfit#60]
Would it be a good idea to implement a `hist` method to PDFs to generate a version suitable for plotting? Or should this be handled by an external function?

**Comment by mayou36** [comment]
I think an external function is the better choice. Somehting like:
`zfit.plot.hist(pdf)`

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #24](https://github.com/zfit/zfit-developement/issues/24) via [**ZenHub**](https://www.zenhub.com/)
