### ISSUE TITLE
Implementation of data loading

### ISSUE THREAD

**Issue by apuignav** [zfit/zfit#8]
Do we want to implement a bit of "scaffolding" to load/cut data? Nothing fancy, just to be able to have `zfit` as standalone as possible.

**Comment by mayou36** [comment]
I am in favour of that. My idea:
- load data from
  + hdf5 with pandas
  + root with [uproot](https://github.com/scikit-hep/uproot)
- cut with pandas/numpy

This results in minimal dependencies.

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #20](https://github.com/zfit/zfit-developement/issues/20) via [**ZenHub**](https://www.zenhub.com/)
