### ISSUE TITLE
sample should return something fixed

### ISSUE THREAD

**Issue by mayou36** [zfit/zfit#83]
Just notes, will be complited later.
If we return a tensor from sampling, this can lead to sampling again every time the graph is run. Usually, we don't want that. So the sample should be stored in a Variable or similar.

Best would be to use the Data object.

**Comment by apuignav** [comment]
I think we need two functions:
  - `sample`, which immediatly returns a dataset
  - `get_sampler`, which can be used as a placeholder to create loss functions and so on, and with a simple `sampler.sample` function we would get the same thing as with `pdf.sample`

**Comment by mayou36** [comment]
Hm, I am not sure about the differences. My idea:

`pdf.sample` returns a `SampleData` (subclass of `Data`) containing the sample (and can be used directly with toys, anything, loss whatever)

`SampleData` holds an additional method `SampleData.resample()` which "updateds" (newly samples) the data. This applies for all the places where the sample was used before (so in the loss etc.)

This should cover everything at once. Or do you have an uncovered/dangerous usecase? Or just a suspicion? (TF is always tricky...)

**Comment by apuignav** [comment]
Yeah, this works too, but you've run TF once more than you need, right?
